title: 'Блог Анатолия Гуляева'
author: 'Анатолий Гуляев'
keywords: 'kaneru, блог, продуктивность, лайфлист, программирование, фронт-енд'
description: > # this means to ignore newlines until "note:"
  Блог Анатолия Гуляева.
  Тут в основном пишу свои наблюдения и заметки про программирование, фронт-енд, продуктивность и свою жизнь.
## note:
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
path: ''
url:  'https://kaneru.me'

permalink: :title/

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true

pagination:
  enabled: true
  collection: 'posts'
  per_page: 5
  permalink: '/page/:num/'
  sort_field: 'date'
  sort_reverse: true

exclude:
- README.md

safe: true
lsi: false

include: [_pages]

plugins: [rouge, jekyll-sitemap, jekyll-feed, jekyll-paginate-v2]

future: true
